crawldata/urls.py
from .models import nEBAYDATA
from django.urls import path

from . import views
from .views import ViewEbay
from .views import IndexView

app_name = 'crawldata'
urlpatterns = [
    path('', IndexView.index, name='index'),
    path('getdataebay/', IndexView.getdataebay, name='getdataebay'),
    path('readweb/', IndexView.readweb, name='readweb'),
    path('ebayapi/', IndexView.ebayapi, name='ebayapi'),
    path('getdataebay3/<int:pk>/', ViewEbay.as_view(), name='nebaydata'),
    path('getdataebay5/', ViewEbay.as_view(), name='search'),
    # path('getdataebay3/<int:question_id>/', views.getdataebay3, name='getdataebay3'),
]

zplus/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('crawldata/', include('crawldata.urls')),
]

crawldata/models.py
from django.db import models

# Create your models here.
import os
from re import S
import requests
from bs4 import BeautifulSoup
import pyttsx3
import gtts
from playsound import playsound
from selenium import webdriver
import time
from io import BytesIO
from urllib.parse import quote

from pydub import AudioSegment
# from pydub.playback import play

class nfNews ():
    def __init__(self, link, numberscroll = 5):
        # self.executable_path='C:/Users/ngocs/OneDrive/Desktop/Ngoc-Zplus/chromedriver.exe'
        self.executable_path='E:/O-N/OneDrive/Desktop/Ngoc-Zplus/chromedriver.exe'
        self.link = link
        self.numberscroll = numberscroll
    
    def getGGnews(self):
        driver = webdriver.Chrome(self.executable_path)
        driver.get (self.link)
        for i in range(1,self.numberscroll):
            driver.execute_script("window.scrollTo(1,5000)")
            time.sleep(3)
        soup = BeautifulSoup(driver.page_source, "html.parser")
        titles = soup.findAll('h3', class_='ipQwMb ekueJc RD0gLb')
        ts = [lk.find('a').text for lk in titles]
        # driver.close()
        driver.quit()
        return ts
    def getnewsdetail(self):
        blacklist = [
            'style',
            'script',
            # other elements,
            ]
        whitelist = [
            'p'
            ]
        url = self.link
        req = requests.get(url)
        soup = BeautifulSoup(req.content, 'html.parser')
        # text_elements = [t for t in soup.find_all(text=True) if t.parent.name not in blacklist]
        text_elements = soup.find('section',class_="enter-24h-cate-article")
        # print (str(text_elements))
        t1 = [t for t in BeautifulSoup(str(text_elements),'html.parser').find_all(text=True) if t.parent.name not in blacklist]
        # titles = soup.findAll('section', class_='enter-24h-cate-article')
        # ts = [te.find('a').text for te in text_elements]
        # ' '.join(t1).split()
        # print (t1)
        return list(filter(lambda x: len(x) > 1, t1))
        # for t2 in t3:
            # print(type(t2))
            # print (len(t2))
            # print (str(t2))


    def speechgglink(self):
        i=0
        for t1 in self.getGGnews():
            i+=1
            print (str(i) + '.'+ t1)
            if (i % 2):
                nfSpeech(t1,"ms").speechtext()
            else:
                nfSpeech(t1,"gg").speechtext()
            if (i >6): break
    def speechdetail(self):
            i=0
            for t1 in self.getnewsdetail():
                i+=1
                print (str(i) + '.'+ t1)
                nfSpeech(t1,"ms").speechtext()

class nfSpeech ():
    def __init__(self, text,voice = "ms"):
        self.text = text
        self.voice = voice
        self.link = 'https://translate.google.com.vn/translate_tts?ie=UTF-8&q='+ quote(text) +'&tl=vi&client=tw-ob'
        self.mp3= self.synthesize_text()
        # self.mp3= ""

    def speechtext(self):
            if (self.voice == "ms"):
                engine = pyttsx3.init()
                # Use male Vietnam voice
                vi_voice_id = "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech\Voices\Tokens\MSTTS_V110_viVN_An"
                engine.setProperty('voice', vi_voice_id)
                engine.setProperty('rate', 200)     # setting up new voice rate
                engine.setProperty('volume',1.0)    # setting up volume level  between 0 and 1
                engine.say(self.text)
                engine.runAndWait()
                engine.stop()
            else:
               
                tts = gtts.gTTS(self.text, lang ="vi", slow = False)
                # mp3_fp = BytesIO()
                # tts.write_to_fp(mp3_fp)
                # mp3_fp.seek(0)
                # song = AudioSegment.from_file(mp3_fp, format="mp3")
                # play(song)
                # playsound(mp3_fp.)
                # mp3_fp.close
                tts.save("tmp.mp3")
                playsound("tmp.mp3")
                os.remove("tmp.mp3")
    def synthesize_text(self):
        tts = gtts.gTTS(self.text, lang ="vi", slow = False)
        mp3_fp = BytesIO()
        tts.write_to_fp(mp3_fp)
        mp3_fp.seek(0)
        song = AudioSegment.from_mp3(mp3_fp)
        return song
    def __str__(self):
            return self.text

class Song(models.Model):
    title= models.TextField()
    artist= models.TextField()
    image= models.ImageField()
    audio_file = models.FileField(blank=True,null=True)
    audio_link = models.CharField(max_length=200,blank=True,null=True)
    duration=models.CharField(max_length=20)
    paginate_by = 2

    def __str__(self):
        return self.title
class nEBAYDATA(models.Model):
    title = models.TextField()
    srcImage = models.CharField(max_length=200,blank=True,null=True)
    link = models.CharField(max_length=200,blank=True,null=True)
    price = models.ImageField()
    trendingprice = models.TextField()
    logistic = models.TextField() 
    sold = models.TextField() 
    cetified = models.TextField()
    star = models.TextField()  
    countreview = models.TextField()
    
    def __str__(self):
        return self.title

crawldata/views.py
from django.shortcuts import render
from django.views import generic
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic.detail import DetailView

import requests
from bs4 import BeautifulSoup
import os
import random
# from selenium.webdriver.common.keys import Keys
from selenium import webdriver
# import chromedriver_binary  # Adds chromedriver binary to path
# from webdriver_manager.chrome import ChromeDriverManager
import time
import json
from django.core.paginator import Paginator
from .models import nfNews 
from .models import nfSpeech
from .models import nEBAYDATA
import datetime
from ebaysdk.exception import ConnectionError
from ebaysdk.finding import Connection
from django.views import generic

from ebaysdk.exception import ConnectionError
from ebaysdk.finding import Connection
from ebaysdk.shopping import Connection as Shopping
from django.conf import settings

# Create your views here.

# class IndexView(generic.ListView):
#     template_name = 'crawldata/index.html'
class IndexView():

    def index(request):
        # return HttpResponse("Hello, world. You're at the polls index." + strftime("%z", gmtime()))
        context = {
            'test': 'test',
        }
        return render(request,"zplus/index.html",context)

    def getdataebay(self,request):
        dt1 = self.do()
        return HttpResponse(dt1)

    def getdata(ebaylink,ScrollNumber):
        driver = webdriver.Chrome()
        # driver = webdriver.Chrome(ChromeDriverManager().install())
        # driver = webdriver.Chrome(executable_path='C:/Users/ngocs/OneDrive/Desktop/Ngoc-Zplus/chromedriver.exe')
        driver.get (ebaylink)
        for i in range(1,ScrollNumber):
            driver.execute_script("window.scrollTo(1,10000)")
            time.sleep(3)
        # print (driver.page_source)
        soup = BeautifulSoup(driver.page_source, "html.parser")
        items = soup.findAll('li', class_='s-item s-item--large s-item--bgcolored')
        # for it in items:
        #     ts = [link.find('a').text for link in titles]
        # ts = [link.find('h3').text for link in items]
        # print(items)    
        # driver.close()
        driver.quit()
        return items
    def showdata(edatas):
        i=0
        for ed in edatas:
            i+=1
        print (str(i) + '.'+ ed)

    def setItem(item):
        # print(item)
        title = "" if item.find('h3') == None else item.find('h3').text
        srcImage="" if item.find('img').attrs["src"] == None else item.find('img').attrs["src"]
        link = "" if item.find('a',attrs={'class':'s-item__link'}).attrs["href"] == None else item.find('a',attrs={'class':'s-item__link'}).attrs["href"]
        price = "" if item.find('span',attrs={'class':'s-item__price'}) == None else item.find('span',attrs={'class':'s-item__price'}).text
        trendingprice = "" if item.select_one("div > span.s-item__trending-price") == None else item.select_one("div > span.s-item__trending-price").text
        logistic = "" if item.find('span',attrs={'class':'s-item__shipping s-item__logisticsCost'}) == None else item.find('span',attrs={'class':'s-item__shipping s-item__logisticsCost'}).text
        sold = "" if item.find('span',attrs={'class':'s-item__hotness s-item__itemHotness'}) == None else item.find('span',attrs={'class':'s-item__hotness s-item__itemHotness'}).text
        cetified = "" if item.select_one("span.s-item__certified-refurbished-badge") == None else item.select_one("span.s-item__certified-refurbished-badge").text
        star = "" if item.select_one("div.b-starrating > span") == None else item.select_one("div.b-starrating > span").text
        countreview = "" if item.select_one("span.s-item__reviews-count > span") == None else item.select_one("span.s-item__reviews-count > span").text
        return [title,srcImage,link,price,trendingprice,logistic,sold,star,countreview]

    # showdata(getdata("https://www.ebay.com/b/PC-Laptops-Netbooks/177/bn_317584"))
    # print (getdata("https://www.ebay.com/b/PC-Laptops-Netbooks/177/bn_317584")

    def do(self):
        i=0
        dtw = list()
        # for dt in getdata("https://www.ebay.com/b/PC-Laptops-Netbooks/177/bn_317584"):
        for dt in self.getdata("https://www.ebay.com/sch/PC-Laptops-Netbooks/177/m.html?_ssn=antonline&_dcat=177&rt=nc&_mPrRngCbx=1&_udlo=400&_udhi=1200"):
            i+=1
            dtw.append(setItem(dt))
            if (i>3):
                break
        return dtw

    # dt1 = do()
    # with open('listfile.txt', 'w') as filehandle:
    #     json.dump(dt1, filehandle)
    #     print(dt1)
        
    def readweb(request):
        obj = nfNews("https://news.google.com/topics/CAAqJggKIiBDQkFTRWdvSUwyMHZNRFZxYUdjU0FuWnBHZ0pXVGlnQVAB/sections/CAQiTENCQVNNd29JTDIwdk1EVnFhR2NTQW5acEdnSldUaUlQQ0FRYUN3b0pMMjB2TURGamNtUTFLZzRLREJJS1Ztbmh1NGQwSUU1aGJTZ0EqKggAKiYICiIgQ0JBU0Vnb0lMMjB2TURWcWFHY1NBblpwR2dKV1RpZ0FQAVAB?hl=vi&gl=VN&ceid=VN%3Avi",1).getGGnews()
        sp = []
        for t1 in obj:
            sp.append(nfSpeech(t1,"ms"))
        paginator= Paginator(sp,7)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context={"page_obj":page_obj}
        return render(request,"zplus/readweb.html",context)

    def ebayapi(request):
    
        try:
            api = Connection(appid='58.187.21.161', config_file=None)
            response = api.execute('findItemsAdvanced', {'keywords': 'legos'})

            assert(response.reply.ack == 'Success')
            assert(type(response.reply.timestamp) == datetime.datetime)
            assert(type(response.reply.searchResult.item) == list)

            item = response.reply.searchResult.item[0]
            assert(type(item.listingInfo.endTime) == datetime.datetime)
            assert(type(response.dict()) == dict)
            arr = response.dict()
            arr = response.dict()
        except ConnectionError as e:
            arr = e.response.dict()
        # print(e)
        # print(e.response.dict())
        context={"arr":arr}
        return render(request,"zplus/ebayapi.html",context)
    def getdataebay3(request, question_id):
            arr = nEBAYDATA()
            arr.title = "abc"
            arr.link = "bcdef"
            return render(request, 'zplus/nebaydata.html', {'arr': arr,'now':"abcd"})

class ViewEbay(generic.TemplateView):
    # def getdataebay2(request):
    #     arr = []

    #     context={"arr":arr}
    #     return render(request,"zplus/getdataebay2.html",context)
    # model = Article
    # paginate_by = 100  # if pagination is desired

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['now'] = timezone.now()
    #     return context
    
    template_name = 'zplus/nebaydata5.html'

    def __init__(self):
        # Initialization of the Strings
        # obj = self.getdata("https://www.ebay.com/b/PC-Laptops-Netbooks/177/bn_317584",1)


        # obj = self.getdata("https://www.ebay.com/b/Dell-Laptops-Netbooks/175672/bn_2780156",1)
        now = datetime.datetime.now()


        # self.extra_context = {'now': now,'obj':obj}

    def getdata(self,link,ScrollNumber):
        # driver = webdriver.Chrome(executable_path='E:/O-N/OneDrive/Desktop/Ngoc-Zplus/chromedriver.exe')
        # driver = webdriver.Chrome(executable_path='C:/Users/ngocs/OneDrive/Desktop/Ngoc-Zplus/chromedriver.exe')
        driver = webdriver.Chrome()
        driver.get (link)
        for i in range(1,ScrollNumber):
            driver.execute_script("window.scrollTo(1,50000)")
            time.sleep(2)
        # print (driver.page_source)
        soup = BeautifulSoup(driver.page_source, "html.parser")
        items = soup.findAll('li', class_='s-item s-item--large s-item--bgcolored')
        eb = []
        for it in items:
            eb.append(self.setItem(it))            
        driver.close()
        driver.quit()
        return eb
    def setItem(self,item):
        # print(item)
        edt = nEBAYDATA()
        edt.title = "" if item.find('h3') == None else item.find('h3').text
        edt.srcImage="" if item.find('img').attrs["src"] == None else item.find('img').attrs["src"]
        edt.link = "" if item.find('a',attrs={'class':'s-item__link'}).attrs["href"] == None else item.find('a',attrs={'class':'s-item__link'}).attrs["href"]
        edt.price = "" if item.find('span',attrs={'class':'s-item__price'}) == None else item.find('span',attrs={'class':'s-item__price'}).text
        edt.trendingprice = "" if item.select_one("div > span.s-item__trending-price") == None else item.select_one("div > span.s-item__trending-price").text
        edt.logistic = "" if item.find('span',attrs={'class':'s-item__shipping s-item__logisticsCost'}) == None else item.find('span',attrs={'class':'s-item__shipping s-item__logisticsCost'}).text
        edt.sold = "" if item.find('span',attrs={'class':'s-item__hotness s-item__itemHotness'}) == None else item.find('span',attrs={'class':'s-item__hotness s-item__itemHotness'}).text
        edt.cetified = "" if item.select_one("span.s-item__certified-refurbished-badge") == None else item.select_one("span.s-item__certified-refurbished-badge").text
        edt.star = "" if item.select_one("div.b-starrating > span") == None else item.select_one("div.b-starrating > span").text
        edt.countreview = "" if item.select_one("span.s-item__reviews-count > span") == None else item.select_one("span.s-item__reviews-count > span").text
        return edt
    
    def get(self, request, *args, **kwargs):
        # form = self.form_class(initial=self.initial)
        # self.template_name = 'https://www.google.com/'
        return render(request, self.template_name, self.extra_context)
    def post(self, request, *args, **kwargs):
        results = None
        query_keywords = ""
        countresult = 0
        if request.method == 'POST':
            try:
                post_data = dict()

crawldata/templates/zplus/ebayapi.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
 <head>
  <meta charset="utf-8"/>
  <title>
   EBAY API
  </title>
  <link href="{% static './style.css' %}" rel="stylesheet"/>
 </head>
 <body>
   EBAY SDK
   <a href="#" class="say">{{arr}}</a>
 </body>
</html>

crawldata/templates/zplus/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'crawldata/style.css' %}">
<link rel="icon" href="{% static 'crawldata/images/favicon.ico' %}">
<h3>TRANG INDEX</h3>

crawldata/templates/zplus/nebaydata.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
 <head>
  <meta charset="utf-8"/>
  <title>
   GET DATA EBAY
  </title>
  <link href="{% static './style.css' %}" rel="stylesheet"/>
 </head>
 <body>
   GET DATA EBAY
  <a href="#" class="now">Now: {{now}}</a>
  <h1>EBAY DATA</h1>
  <ul>
  {% for edt in obj %}
      <li><a href = '{{ edt.link }}'>{{ edt.title }}|{{ edt.price }}|{{ edt.trendingprice }}|{{ edt.sold }}</a></li>
  {% empty %}
      <li>No articles yet.</li>
  {% endfor %}
  </ul>
 </body>
</html>

crawldata/templates/zplus/nebaydata2.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>jQuery Auto Tables Plugin Example</title>
  <link href="{% static './zplus/style.css' %}" rel="stylesheet"/>
  <!-- <link href="https://www.jqueryscript.net/css/jquerysctipttop.css" rel="stylesheet" type="text/css"> -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/4.5.2/materia/bootstrap.min.css">

  <!-- jquery -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

  <!-- popper -->
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

  <!-- bootstrap -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

  <!-- autotables -->
  <script src="{% static './zplus/auto-tables.js' %}"></script>
  <style>
    body { background-color: #fafafa; }
    .container { margin: 150px auto; }
    thead th { cursor: pointer; }
  </style>

</head>
<body>
<!-- <div id="jquery-script-menu">
<div class="jquery-script-center">
  <div id="carbon-block"></div>
  <div class="jquery-script-clear"></div>
</div>
</div> -->
<div class="container1">

    <input type="text" class="form-control mb-3 tablesearch-input" data-tablesearch-table="#data-table"  placeholder="Search">

    <div class="table-responsive">

      <table id="data-table" class="table tablesearch-table table-bordered table-striped">
        <thead><tr>
          <th>Title</th>
          <th>Price</th>
          <th>Trending Price</th>
          <th>sold</th>
        </tr></thead>
        <tbody>
          {% for edt in obj %}
            <tr>
              <td><a href = '{{ edt.link }}'>{{edt.title}}</a></td>
              <td>{{edt.price}}</td>
              <td>{{edt.trendingprice}}</td>
              <td>{{edt.sold}}</td>
            </tr>
          {% empty %}
            <p>No articles yet.</p>
          {% endfor %}
        </tbody>
      </table>
    </div>


    <script>

      $(document).ready(function() {

        var headers = $('#data-table thead th');

        $(headers[5]).attr('data-tablesort-type', 'date');


        $('table').not(".tablesort").addClass('tablesort');
        // $('')

      });


    </script>
  </body>
  </html>

crawldata/templates/zplus/nebaydata5.html
{% load static %}
{% load nFunction1 %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>jQuery Auto Tables Plugin Example</title>
  <link href="{% static './zplus/style.css' %}" rel="stylesheet"/>
  <!-- <link href="https://www.jqueryscript.net/css/jquerysctipttop.css" rel="stylesheet" type="text/css"> -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/4.5.2/materia/bootstrap.min.css">

  <!-- jquery -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

  <!-- popper -->
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

  <!-- bootstrap -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

  <!-- autotables -->
  <script src="{% static './zplus/auto-tables.js' %}"></script>
  <style>
    body { background-color: #fafafa; }
    .container { margin: 150px auto; }
    thead th { cursor: pointer; }
  </style>

</head>
<body>
<!-- <div id="jquery-script-menu">
<div class="jquery-script-center">
  <div id="carbon-block"></div>
  <div class="jquery-script-clear"></div>
</div>
</div> -->
<div class="container1">
    <form action="{% url 'crawldata:search' %}" method="post">
      {% csrf_token %}  
      <input type="text" class="form-control mb-3 keywords-input"  placeholder="Key Words" name="keywords" value='{{keywords}}'>
      <p>Result: {{countresult}} Items (keyword: {{keywords_result}})</p>
      <input type="submit" class="form-control mb-3 submit-input"  value="Search"> 
    </form> 
    <input type="text" class="form-control mb-3 tablesearch-input" data-tablesearch-table="#data-table"  placeholder="Filter">

    <div class="table-responsive">

      <table id="data-table" class="table tablesearch-table table-bordered table-striped">
        <thead><tr>
          <th>Title</th>
          <th>Category Name</th>
          <th>Condition</th>
          <th>Price</th>
          <th>Trending Price</th>
          <th>Watch</th>
          <th>Sold</th>
          <th>new1</th>
        </tr></thead>
        <tbody>
          
          {% for value in obj %}
              <tr>
                <td><a href = '{{value.viewItemURL}}'>{{value.title}}</a></td>
                <td>{{value.primaryCategory.categoryName}}</td>
                <td>{{value.condition.conditionDisplayName}}</td>
                <td>{{value.sellingStatus.currentPrice.value}}</td>
                <td>{{value.discountPriceInfo}}</td>
                <td>{{value.listingInfo.watchCount}}</td>
                <td>{{value.subtitle}}</td>
                <td>{{value}}</td>
              </tr>
        
          {% empty %}
            <p>No articles yet.</p>
          {% endfor %}
        </tbody>
      </table>
    </div>


    <script>

      $(document).ready(function() {

        var headers = $('#data-table thead th');

        $(headers[0]).attr('data-tablesort-type', 'string');
        $(headers[1]).attr('data-tablesort-type', 'string');
        $(headers[2]).attr('data-tablesort-type', 'string');
        $(headers[4]).attr('data-tablesort-type', 'string');
        $(headers[5]).attr('data-tablesort-type', 'int');
        $(headers[6]).attr('data-tablesort-type', 'int');
        $(headers[7]).attr('data-tablesort-type', 'int');
        $('table').not(".tablesort").addClass('tablesort');
        // $('')

      });


    </script>
  </body>
  </html>